//
// Created by Yihua Liu on 2024/3/31.
//

#ifndef SUISAPP_OPTIC_MATERIAL_H
#define SUISAPP_OPTIC_MATERIAL_H

#include <vector>
#include <QList>
#include <QObject>
#include <QString>

enum class DbType {
    DF, SOLCORE
};

class OpticMaterial : QObject {
    Q_OBJECT

    Q_PROPERTY(QString mat_name READ matName WRITE setMatName NOTIFY matNameChanged)
    Q_PROPERTY(QList<double> n_wl READ nWl NOTIFY nWlChanged)
    Q_PROPERTY(QList<double> n_data READ nData NOTIFY nDataChanged)

public:
    OpticMaterial(QString mat_name, std::vector<double>& n_wl, std::vector<double>& n_vec,
                  std::vector<double>& k_wl, std::vector<double>& k_vec);

    [[nodiscard]] QString matName() const;
    void setMatName(const QString& name);

    [[nodiscard]] QList<double> nWl() const;
    [[nodiscard]] QList<double> nData() const;

signals:
    void matNameChanged();  // implementation will automatically be generated by MOC
    void nWlChanged();
    void nDataChanged();

private:
    DbType db_type;
    QString mat_name;
    std::vector<double> n_wl;
    std::vector<double> n_data;
    std::vector<double> k_wl;
    std::vector<double> k_data;
};


#endif  // SUISAPP_OPTIC_MATERIAL_H
